### ISSUE TITLE
Add more instruments

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#11]
That the user can play, when creating a profile. Currently we only have 3 to choose from when creating/modifying profile.

**Comment by stefano-tech-ai** [comment]
Should this be done manually? Or are you planning to add an administration page?

**Comment by mildanor** [comment]
I think we wanted to either important a list of instruments from somewhere or we need to add more instruments to the data file we currently have. Currently yes, list of instruments was created manually I think.

**Comment by stefano-tech-ai** [comment]
@mildanor you can reference this [file](https://github.com/alessandrocapra/jammin-react/blob/master/src/data/instruments.js) and try to add new instruments! You only need to copy the structure of the other 3 instruments and change their values
