### ISSUE TITLE
Update database with venue info and link it to venue.js and venuepage.js

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#15]
![screen shot 2016-12-19 at 00 53 43](https://cloud.githubusercontent.com/assets/16984074/21297308/00c2db64-c586-11e6-821a-a794f4afebd6.png)

Venue info can be found here:

https://docs.google.com/document/d/1QYTFpZ2RWgfBK_jHIY-M5dgY5TxznColmM2booSLSZs/edit

Currently only venue description updates from the data base but not image, title or address/contact. Should we have some consistency? As in if we have the venue description from the database, shouldn't we also have venue titles and contact infos coming from there too?

I also think that since the type of information we have on the venues is unconsistent and quite difficult to standardize this could be done as a static page without the link to the database and I could do it but I don't know how to unlink the database from the page..

Let me know which option you prefer!

**Comment by alessandrocapra** [comment]
I checked the page and it seems quite fine content-wise to me, I will close the issue. If I'm wrong, just reopen it @mildanor ;)
