### ISSUE TITLE
Allow users to see people playing in a range around their city

### ISSUE THREAD

**Issue by alessandrocapra** [alessandrocapra/jammin-react#2]

**Comment by alessandrocapra** [comment]
Idea: allow users to save more than one location, for instance Helsinki and Espoo. We can rename this as "Where are you able to jam?" instead of where you live. @stefanomunarini @mildanor

**Comment by mildanor** [comment]
Sounds good if you guys have the time to implement it.

But just to save as a preference in user profile, rather than in the search field (on the homepage), right?

**Comment by alessandrocapra** [comment]
Yessa! Sorry just saw this

**Comment by alessandrocapra** [comment]
Fixed following the idea in the previous comments, check it out @mildanor!
