### ISSUE TITLE
Registration page changes

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#23]
I redid the registration page.

Now it looks like this :
![screen shot 2016-12-19 at 23 55 11](https://cloud.githubusercontent.com/assets/16984074/21330566/be042e6a-c646-11e6-854b-9a7d6ff64b54.png)

The problem is that since I only did the front end; the back end for it is just like it was previously:  so both sign in (for existing) and sign up (for new user) fields functionality wise are still totally the same. They only work for registering new user. You'll notice this if you start typing in the form - one is basically a mirror of the other.

If you think that usability wise having the two separate fields for existing and new users is good, then could someone fix this functionality/firebase bits?

Hope the explanation makes sense.

**Comment by alessandrocapra** [comment]
Fixed functionality!
