### ISSUE TITLE
Facebook login doesn't save the user data on Firebase database! Also redirect to profile page doesn't work

### ISSUE THREAD

**Issue by alessandrocapra** [alessandrocapra/jammin-react#25]

**Comment by mildanor** [comment]
I tried to register on facebook today using my grandmothers facebook. Didnt work at all. I wasnt redirected to edit profile page and she didnt show up in firebase as far as I could tell as a new user. 

@alessandrocapra what's the status of this? Maybe let's not do the Facebook thing as there is little time left and it doesnt appear to be working?

**Comment by stefano-tech-ai** [comment]
Yeah @mildanor it is not working. No one has ever done this piece of work, so I'd suggest to remove it and only leave Google as external signup option.

**Comment by alessandrocapra** [comment]
I agree with @stefanomunarini, let's remove it for now, maybe in the future, who knows.. :P
