### ISSUE TITLE
Integrating the genres list to profile and search

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#27]
I made a music genres list in scr/data/genres.js 

We should use it and integrate it with 'Genres I play' label instead of 'Influences' as it is now and keep 'Artists listened to' as it is.

![screen shot 2016-12-20 at 13 54 43](https://cloud.githubusercontent.com/assets/16984074/21349785/7ada1ff2-c6bc-11e6-8ea4-930b4a39c674.png)

Also when you do it don't forget to modify this and the labels in Profile and Edit Profile pages so that everything is consistent.

![screen shot 2016-12-20 at 14 05 41](https://cloud.githubusercontent.com/assets/16984074/21349950/6b633440-c6bd-11e6-932c-508ffb9222c8.png)

**Comment by stefano-tech-ai** [comment]
So I suppose that this update affects the Edit Profile as well, right?

**Comment by mildanor** [comment]
Yes it should .

**Comment by alessandrocapra** [comment]
@mildanor @stefanomunarini I think it works fine now, check it please ;)

**Comment by mildanor** [comment]
Hey, Yup, just checked! Good job ! I can add more genres later when I have time, as currently there are only 5 available? @alessandrocapra But of course it's not really an issue.

**Comment by alessandrocapra** [comment]
Yeah sure, feel free to add all the genres you can find :dancer:

**Comment by stefano-tech-ai** [comment]
Actually @mildanor all the genres are in the data file, but they are commented out because in the wrong format. The right format is an object, not an array.

Like this:

        {
             "value": "Blues",
             "label": "Blues",
        },

instead of a simple array of String.

**Comment by mildanor** [comment]
Ok cool, thanks.
