### ISSUE TITLE
Fixing styling and layout in search page

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#28]
![screen shot 2016-12-20 at 13 54 43](https://cloud.githubusercontent.com/assets/16984074/21349995/ae81d218-c6bd-11e6-89d5-e2b401b1e141.png)

1) Currently the artists listened to on the search page, near each profile appear at random order - if there is a way to style it and make it more consistent would be nice to fix this.

2) ~~Also, all the profiles pics next to user names should be the same size and shape - now some are bigger than others.~~
![screen shot 2016-12-20 at 14 02 49](https://cloud.githubusercontent.com/assets/16984074/21350020/d5753bbc-c6bd-11e6-8f7a-f3910bdbcdde.png)

3) ~~While we are at it Availability/ 2 times a week is very close to influences label (text) - would be nice to increase the distance between them/style it otherwise looks a bit confusing for the user.~~

@alessandrocapra if you don't find to do it I can try when I'm back to Lithuania from 25th Dec onwards.

**Comment by alessandrocapra** [comment]
Fixed the label spacing for now, the easiest one

**Comment by alessandrocapra** [comment]
@stefanomunarini do you think it's possible to order the checkboxes, either by number of occurences or alphabetically? Can you take this?

**Comment by stefano-tech-ai** [comment]
See PR
