### ISSUE TITLE
Language affects location in search

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#3]
Helsinkis in Lithuanian, suggested by google didn't display any results - wasn't recognised as Helsinki.

Object 1 or 2 in the console was the only one that matched the name of the city in both languages.
Attached is image of Lithuanian version.
![screen shot 2016-12-14 at 13 06 20](https://cloud.githubusercontent.com/assets/16984074/21179848/97d61150-c1fe-11e6-801e-8495d2c73f61.png)

**Comment by alessandrocapra** [comment]
@mildanor I think this can be close, we have no time for this..ok?
