### ISSUE TITLE
Process of prompting unregistered user to register 

### ISSUE THREAD

**Issue by mildanor** [alessandrocapra/jammin-react#36]
When you are an unregistered user, and you are looking at a full profile of a musician you found through a search, you are not able to see contact me button.

I think it should be visible to them and when clicking on it it should take them to registration page. This is because otherwise navigation wise their user journey is confusing. What are they supposed to do next after ? There is no clear call to action.

However, if the user is registered then after clicking on contact me button they should be either shown a modal or the mail thing Stefano did.

@alessandrocapra what do you think ?

**Comment by alessandrocapra** [comment]
@mildanor now the mailto works, should we do something else? Can we close this issue?

**Comment by alessandrocapra** [comment]
@mildanor I added a modal that shows up only when users are not registered, otherwise the mailto is used to contact others. 
Use `npm install` to install a package for the modals and try it, I will close the issue for now. Re-open it here if you see something is not working!
