### ISSUE TITLE
Search breaks if one user has not set a music_listen artist (probably other similar fields)

### ISSUE THREAD

**Issue by alessandrocapra** [alessandrocapra/jammin-react#7]

**Comment by alessandrocapra** [comment]
Fixed by adding control if the field is empty (@stefanomunarini sorry, didn't see you were working on it)

**Comment by stefano-tech-ai** [comment]
@alessandrocapra I updated the code to delete duplicates from "music_play" and "music_listen" in the  SearchResultPage and changed a bit their structures, so your updates might get reverted.

You can reference this commit baeaae0e31cef8ff92fa8032f94b6870b6002d16

**Comment by stefano-tech-ai** [comment]
And in the same commit you can see that I am trying to save a counter for every influencer/music player so that we can show something like

Queen (4)
Helsl(2)
Beatles (3)
Mosca (1)
